### ISSUE TITLE
升级新版本后 部分手机出现X5WebView初始化时空指针异常

### ISSUE THREAD

**Issue by fangxiong** [yangchong211/YCWebView#108]
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tencent.smtt.export.external.extension.interfaces.IX5WebSettingsExtension.setDayOrNight(boolean)' on a null object reference
     at com.ycbjie.webviewlib.view.BaseWebView.setDayOrNight(Unknown Source:4)
    at com.ycbjie.webviewlib.view.X5WebView.initWebViewSettings(Unknown Source:94)
    at com.ycbjie.webviewlib.view.X5WebView.<init>(Unknown Source:3)

**Comment by conscious01** [comment]
same problem here

**Comment by taojr95** [comment]
如果X5未初始化完成前，调用了代码就会报这个错

**Comment by lianghuacheng** [comment]
X5 内核没加载成功就会这样。我也碰到了

**Comment by lianghuacheng** [comment]
这个问题该怎么弄呢？

**Comment by taojr95** [comment]
> 这个问题该怎么弄呢？

![image](https://user-images.githubusercontent.com/37699177/124420930-0cd2ba80-dd93-11eb-8279-90c5aec50675.png)
把这行注释了就行

**Comment by Gems-os** [comment]
点进去，然后把setDayOrNight的实现改成super.setDayOrNight;
