### ISSUE TITLE
demo跑不起来了

### ISSUE THREAD

**Issue by 932707629** [yangchong211/YCWebView#124]
Process: com.ycbjie.ycwebview, PID: 4392
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ycbjie.ycwebview/com.ycbjie.ycwebview.WebViewActivity}: android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class com.ycbjie.webviewlib.view.X5WebView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3554)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3738)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7779)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
     Caused by: android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class com.ycbjie.webviewlib.view.X5WebView
     Caused by: android.view.InflateException: Binary XML file line #60: Error inflating class com.ycbjie.webviewlib.view.X5WebView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.ycbjie.ycwebview.WebViewActivity.onCreate(WebViewActivity.java:84)
        at android.app.Activity.performCreate(Activity.java:7458)
        at android.app.Activity.performCreate(Activity.java:7448)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3533)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3738)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7779)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.tencent.smtt.export.external.extension.interfaces.IX5WebSettingsExtension.setDayOrNight(boolean)' on a null object reference
        at com.ycbjie.webviewlib.view.BaseWebView.setDayOrNight(BaseWebView.java:262)

**Comment by geekzxiang** [comment]
是的，demo有问题

**Comment by geekzxiang** [comment]
![image](https://user-images.githubusercontent.com/5501481/163383074-f65849d7-6ccb-467f-81a9-a12d75b55fec.png)
打包有问题，没代码

**Comment by 932707629** [comment]
换其他版本？

**Comment by geekzxiang** [comment]
> 换其他版本？

直接改成依赖本地库，不依赖远程版本
