### ISSUE TITLE
加载视频闪退Attempt to invoke interface method 'void com.ycbjie.webviewlib.VideoWebListener.hindWebView()' on a null object reference

### ISSUE THREAD

**Issue by richfuns** [yangchong211/YCWebView#53]
这是日志, activity的硬件加速关闭了

`2019-11-29 17:05:40.973 5711-5895/? I/clp-JNI: Add pinfo.  (channel) 8938cf7 com.pla.fucker/org.cocos2dx.javascript.WebActivity (server) (pkg) AppWindowToken{5439407 token=Token{4127a46 ActivityRecord{e962621 u0 com.pla.fucker/org.cocos2dx.javascript.WebActivity t786}}} 7362 10332 (action) 1
2019-11-29 17:05:40.974 7362-7362/com.pla.fucker W/com.pla.fucker: Attempt to remove non-JNI local reference, dumping thread
2019-11-29 17:05:40.977 7362-7362/com.pla.fucker D/ViewRootImpl@63e3f34[WebActivity]: ViewPostIme pointer 0
2019-11-29 17:05:40.982 7362-7362/com.pla.fucker D/ViewRootImpl@63e3f34[WebActivity]: ViewPostIme pointer 1
2019-11-29 17:05:41.355 7362-7362/com.pla.fucker W/com.pla.fucker: Attempt to remove non-JNI local reference, dumping thread
2019-11-29 17:05:41.739 7362-7362/com.pla.fucker W/com.pla.fucker: Attempt to remove non-JNI local reference, dumping thread
2019-11-29 17:05:41.743 7362-7362/com.pla.fucker D/InputMethodManager: HSIFW - flag : 0 Pid : 7362
2019-11-29 17:05:41.753 5711-11481/? D/ActivityManager: setRequestedOrientation(0) from com.pla.fucker
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err: java.lang.NullPointerException: Attempt to invoke interface method 'void com.ycbjie.webviewlib.VideoWebListener.hindWebView()' on a null object reference
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at com.ycbjie.webviewlib.X5WebChromeClient.onShowCustomView(X5WebChromeClient.java:211)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at com.tencent.smtt.sdk.f.onShowCustomView(SmttWebChromeClient.java:228)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at com.tencent.tbs.core.webkit.tencent.TencentWebChromeClient.onShowCustomView(TbsJavaCore:309)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at android.webview.chromium.WebViewContentsClientAdapter.onShowCustomView(TbsJavaCore:1174)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at android.webview.chromium.tencent.TencentWebViewContentsClientAdapter.onShowCustomView(TbsJavaCore:2598)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at org.chromium.android_webview.AwWebContentsDelegateAdapter.enterFullscreen(TbsJavaCore:309)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at org.chromium.android_webview.AwWebContentsDelegateAdapter.toggleFullscreenModeForTab(TbsJavaCore:273)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at org.chromium.base.SystemMessageHandler.handleMessage(TbsJavaCore:51)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at android.os.Looper.loop(Looper.java:214)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7050)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-11-29 17:05:41.754 7362-7362/com.pla.fucker W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
2019-11-29 17:05:41.755 7362-7362/com.pla.fucker W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2019-11-29 17:05:41.758 7362-7362/com.pla.fucker E/CrashHandler: In thread: Thread[main,5,main]
    UncaughtException detected: java.lang.NullPointerException: Attempt to invoke interface method 'void com.ycbjie.webviewlib.VideoWebListener.hindWebView()' on a null object reference
        at com.ycbjie.webviewlib.X5WebChromeClient.onShowCustomView(X5WebChromeClient.java:211)
        at com.tencent.smtt.sdk.f.onShowCustomView(SmttWebChromeClient.java:228)
        at com.tencent.tbs.core.webkit.tencent.TencentWebChromeClient.onShowCustomView(TbsJavaCore:309)
        at android.webview.chromium.WebViewContentsClientAdapter.onShowCustomView(TbsJavaCore:1174)
        at android.webview.chromium.tencent.TencentWebViewContentsClientAdapter.onShowCustomView(TbsJavaCore:2598)
        at org.chromium.android_webview.AwWebContentsDelegateAdapter.enterFullscreen(TbsJavaCore:309)
        at org.chromium.android_webview.AwWebContentsDelegateAdapter.toggleFullscreenModeForTab(TbsJavaCore:273)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(TbsJavaCore:51)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
2019-11-29 17:05:41.758 7362-7362/com.pla.fucker I/crash_recorder: recordTbsCrash:
     {java.lang.NullPointerException: Attempt to invoke interface method 'void com.ycbjie.webviewlib.VideoWebListener.hindWebView()' on a null object reference
        at com.ycbjie.webviewlib.X5WebChromeClient.onShowCustomView(X5WebChromeClient.java:211)
        at com.tencent.smtt.sdk.f.onShowCustomView(SmttWebChromeClient.java:228)
        at com.tencent.tbs.core.webkit.tencent.TencentWebChromeClient.onShowCustomView(TbsJavaCore:309)
        at android.webview.chromium.WebViewContentsClientAdapter.onShowCustomView(TbsJavaCore:1174)
        at android.webview.chromium.tencent.TencentWebViewContentsClientAdapter.onShowCustomView(TbsJavaCore:2598)
        at org.chromium.android_webview.AwWebContentsDelegateAdapter.enterFullscreen(TbsJavaCore:309)
        at org.chromium.android_webview.AwWebContentsDelegateAdapter.toggleFullscreenModeForTab(TbsJavaCore:273)
        at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
        at org.chromium.base.SystemMessageHandler.handleMessage(TbsJavaCore:51)
    	at android.os.Handler.dispatchMessage
2019-11-29 17:05:41.759 7362-7362/com.pla.fucker I/crash_recorder: isInTbsContext, webviewType: X5InitJava, isLoading: 1
2019-11-29 17:05:41.768 7362-9743/com.pla.fucker D/JIGUANG-JCommon: [JCommonInterface] onEvent action:deviceinfo
2019-11-29 17:05:41.806 7362-9743/com.pla.fucker W/com.pla.fucker: Accessing hidden method Landroid/telephony/TelephonyManager;->getSimCount()I (light greylist, reflection)
2019-11-29 17:05:41.806 7362-9743/com.pla.fucker W/com.pla.fucker: Accessing hidden method Landroid/telephony/TelephonyManager;->getSimSerialNumber(I)Ljava/lang/String; (light greylist, reflection)
2019-11-29 17:05:41.806 7362-9743/com.pla.fucker W/com.pla.fucker: Accessing hidden method Landroid/telephony/TelephonyManager;->getSubscriberId(I)Ljava/lang/String; (light greylist, reflection)
2019-11-29 17:05:41.807 7362-9743/com.pla.fucker W/com.pla.fucker: Accessing hidden method Landroid/telephony/SubscriptionManager;->getSubId(I)[I (light greylist, reflection)
2019-11-29 17:05:41.822 7362-9743/com.pla.fucker E/JIGUANG-JCore: [ReportUtils] wrap data failed`

请问这是哪里的问题？ 谢谢

**Comment by jeremaihloo** [comment]
```
html_view_content.webChromeClient = X5WebChromeClient(activity!!).apply {
            setVideoWebListener(object : VideoWebListener {
                override fun showWebView() {

                }

                override fun showVideoFullView() {

                }

                override fun hindWebView() {

                }

                override fun hindVideoFullView() {

                }

            })
        }
```
就好了，日志都告诉你了，你都不看日志的吗
